config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get 'welcome/index'

  get 'welcome/login' => 'users#login'
  get 'logout' => 'sessions#logout'
  get 'addfriend' => 'users#add_friend'
  get 'sentmessages' => 'private_messages#sent_messages'

  resources :users
  resources :sessions
  resources :private_messages

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id", :class_name => "User"
  belongs_to :friend, :foreign_key => "friend_id", :class_name => "User"
end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships, :foreign_key => "user_id",
           :class_name => "Friendship"
  has_many :friends, :through => :friendships

  has_many :sent_messages, :class_name => 'PrivateMessage', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'PrivateMessage', :foreign_key => 'recipient_id'

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in, :message_count

  def current_user
    if session[:user_id]
      User.find_by_id(session[:user_id])
    end
  end

  def message_count
    PrivateMessage.where(receiver_id: current_user.id).count
  end

  def signed_in
    current_user.present?
  end

  def require_login
    unless signed_in
      flash[:error] = "You must sign in to see this page"
      redirect_to welcome_login_path
    end
  end

  def skip_if_logged_in
    if signed_in
      redirect_to users_path
    end
  end
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :require_login

  def index
    @messages = PrivateMessage.where(receiver_id: current_user.id).order(:created_at)
    @friends = Friendship.where(user_id: current_user.id).map { |f| User.find(f.friend_id) }
  end

  def create
    @private_message = PrivateMessage.new(
        content: params[:private_message][:content],
        receiver_id: params[:private_message][:receiver_id],
        sender_id: current_user.id,
        unread: true
    )
    @private_message.save

    flash[:notice] = "Message sent successfully!"
    redirect_to private_messages_path
  end

  def show
    @message = PrivateMessage.find(params[:id])

    if @message.unread?
      @message.unread = false
      @message.save
    else
      flash[:warning] = "You already read this message!"
      redirect_to private_messages_path
    end

  end

  def sent_messages
    @messages = PrivateMessage.where(sender_id: current_user.id).order(:created_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
  def create
    @user = User.find_by_email(params[:user][:email])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome back!"
      redirect_to private_messages_path
    else
      flash[:error] = "Email or password is incorrect!"
      redirect_to welcome_login_path
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "You have been logged out!"
    redirect_to welcome_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: [:index, :add_friend]
  before_action :skip_if_logged_in, only: [:login]

  def new
    @user = User.new
  end

  def index
    @users = User.order(:name)
    @friends = Friendship.where(user_id: current_user.id).map { |f| User.find(f.friend_id) }
    @friends = @friends << current_user
    @users = @users - @friends
  end

  def create
    @user = User.new(user_params)
    @user.image_url = "https://randomuser.me/api/portraits/med/women/#{User.count}.jpg"

    if @user.save
      session[:user_id] = @user.id
      redirect_to private_messages_path
    else
      redirect_to welcome_index_path
    end
  end

  def login

  end

  def add_friend
    @friendship = Friendship.new(user_id: current_user.id, friend_id: params[:friend])
    @friend = User.find(params[:friend])

    if @friendship.save
      flash[:notice] = "#{@friend.name} has been added to your friend list!"
      redirect_to users_path
    else
      flash[:error] = "Oops! An error has occured!"
      redirect_to users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :skip_if_logged_in, only: [:index]

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', warning: 'alert-warning', notice: 'alert-info'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>    
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <nav class="navbar navbar-light bg-faded">
    <%= flash_messages %>

    <!-- Toggle Button -->
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#nav-content">
      &#9776;
    </button>
    <!-- Nav Content -->
    <div class="collapse navbar-toggleable-xs" id="nav-content">
      <a class="navbar-brand" href="/"><%= image_tag 'logo-small' %></a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= welcome_index_path %>">Sign Up</a>
        </li>
        <li class="nav-item">
          <% if signed_in %>
              <a class="nav-link" href="<%= logout_path %>">Sign out</a>
          <% else %>
            <a class="nav-link" href="<%= welcome_login_path %>">Sign In</a>
          <% end %>
        </li>
        <% if signed_in %>
            <li class="nav-item">
              <a class="nav-link" href="<%= private_messages_path %>">
                Messages (<%= message_count %>)
              </a>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/private_messages/index.html.erb
<div class="container">
  <div style="margin: 40px 0 40px 0">
    <% @messages.each do |m| %>
        <div class="row" style="margin: 10px 0 10px 0">
          <div class="col-sm-1">
            <img src="<%= User.find(m.sender_id).image_url %>" style="height: 50px; width: 50px">
          </div>
          <div class="col-sm-8">
            <h4 style="margin-top: 0">From: <%= User.find(m.sender_id).name %></h4>
            <p>
              <% if m.content.length > 80 %>
                  <%= m.content[0..80] %>...
              <% else %>
                  <%= m.content %>
              <% end %>
            </p>
            <%= link_to "Read more", private_message_path(m) %>
          </div>
          <div class="col-sm-3" style="padding: 10px">
            <% unless m.unread? %>
              <%= image_tag 'check', width: 20, height: 20 %>
            <% end %>
          </div>
        </div>
        <hr/>
    <% end %>
  </div>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#messageModal">New Message</button>
  <%= link_to "Add Friends", users_path, class: "btn btn-primary" %>
  <%= link_to "Sent Message", sentmessages_path, class: "btn btn-primary" %>
</div>

<!-- Modal -->
<div id="messageModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Message</h4>
      </div>
      <div class="modal-body">
        <%= form_for(PrivateMessage.new) do |f| %>
            <div class="form-group">
              <%= f.label :receiver_id %>
              <%= f.select(:receiver_id, Hash[@friends.map { |f| [f.name, f.id] }], {}, {class: "form-control"}) %>
            </div>
            <div class="form-group">
              <div class="form-group">
                <%= f.label :content %>
                <%= f.text_area "content", class: "form-control", rows: 5 %>
              </div>
            </div>
            <div class="form-group text-center">
              <%= f.submit 'Send', class: 'btn btn-info' %>
            </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/private_messages/sent_messages.html.erb
<div class="container">
  <div style="margin: 40px 0 40px 0">
    <% @messages.each do |m| %>
        <div class="row" style="margin: 10px 0 10px 0">
          <div class="col-sm-1">
            <img src="<%= User.find(m.receiver_id).image_url %>" style="height: 50px; width: 50px">
          </div>
          <div class="col-sm-8">
            <h4 style="margin-top: 0">To: <%= User.find(m.receiver_id).name %></h4>
            <p>Oops! As stated in the assignment, you are not allowed to read your own message!</p>
          </div>
          <div class="col-sm-3" style="padding: 10px">
            <% if m.unread? %>
              Unread
            <% else %>
              <%= m.updated_at %>
            <% end %>
          </div>
        </div>
        <hr/>
    <% end %>
  </div>
  <%= link_to "Back", private_messages_path, class: "btn btn-primary" %>
</div>

app/views/private_messages/show.html.erb
<div class="container">
  <div class="row" style="margin: 40px 0 40px 0">
    <div class="col-sm-1">
      <img src="<%= User.find(@message.sender_id).image_url %>" style="height: 50px; width: 50px">
    </div>
    <div class="col-sm-8">
      <h4 style="margin-top: 0">From: <%= User.find(@message.sender_id).name %></h4>
      <p>
        <%= @message.content %>
      </p>
    </div>
  </div>
  <%= link_to "Back", private_messages_path, class: "btn btn-primary" %>
</div>

app/views/users/_user.html.erb
<div class="col-xs-12 col-md-4">
  <div class="card card-<%= cycle('male', 'female') %>">
    <%= image_tag user.try(:image_url) %>
    <div class="card-block">
      <h4 class="card-title"><%= user.try(:name) %></h4>
      <%= link_to "Add", addfriend_path(friend: user.try(:id) ), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container users-index">
  <% @users.in_groups_of(3) do |group| %>
    <div class="row">
      <%= render partial: 'user', collection: group.compact %>
    </div>
  <% end %>

</div>

app/views/users/login.html.erb
<section class="header-11-sub">
  <div class="background">&nbsp;</div>
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h3>The Chatting Site for Ruby Addicts</h3>
        <p>Inside, Ruby is the official language. English is not allowed!</p>
        <div class="signup-form">
          <%= form_for :user, url: sessions_path do |f| %>
              <div class="form-group">
                <%= f.text_field 'email', class: 'form-control', placeholder: 'Your E-mail' %>
              </div>
              <div class="form-group">
                <div class="half-width">
                  <%= f.password_field 'password', class: 'form-control', placeholder: 'Password' %>
                </div>
              </div>
              <div class="form-group">
                <%= f.submit 'Login', class: 'btn btn-block btn-info' %>
              </div>
          <% end %>
        </div>
        <div class="additional-links">By signing up you agree to <a href="#">Terms of Use</a> and <a href="#">Privacy</a></div>
      </div>
      <div class="col-sm-7 col-sm-offset-1 player-wrapper">
        <div class="player">
          <%= image_tag 'hero' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
  <section class="header-11-sub">
      <div class="background">&nbsp;</div>
      <div class="container">
          <div class="row">
              <div class="col-sm-4">
                  <h3>The Chatting Site for Ruby Addicts</h3>
                  <p>Inside, Ruby is the official language. English is not allowed!</p>
                  <div class="signup-form">
                    <%= form_for(User.new) do |f| %>
                      <div class="form-group">
                        <%= f.text_field 'email', class: 'form-control', placeholder: 'Your E-mail' %>
                      </div>
                       <div class="form-group">
                        <%= f.text_field 'name', class: 'form-control', placeholder: 'Name' %>
                      </div>
                      <div class="form-group">
                        <div class="half-width">
                          <%= f.password_field 'password', class: 'form-control', placeholder: 'Password' %>
                        </div>
                        <div class="half-width">
                          <%= f.password_field 'password_confirmation', class: 'form-control', placeholder: 'Confirmation' %>          
                        </div>  
                      </div>
                      <div class="form-group">
                          <%= f.submit 'Sign Up', class: 'btn btn-block btn-info' %>
                      </div>    
                    <% end %>
                  </div>  
                  <div class="additional-links">By signing up you agree to <a href="#">Terms of Use</a> and <a href="#">Privacy</a></div>
              </div>
              <div class="col-sm-7 col-sm-offset-1 player-wrapper">
                  <div class="player">
                      <%= image_tag 'hero' %>
                  </div>
              </div>
          </div>
      </div>
  </section>